FROM node:23-alpine

WORKDIR /app

EXPOSE 8000

RUN corepack enable && corepack prepare pnpm@9.14.4 --activate

COPY package.json ./
COPY pnpm-lock.yaml* ./
RUN pnpm install

ENV NEXT_TELEMETRY_DISABLED 1

CMD ["pnpm", "run", "dev", "--port", "8000"]
